### ISSUE TITLE
Spawned Stars and CelestialBodies 

### ISSUE THREAD

**Issue by ThomasKerman** [BryceSchroeder/Kopernicus#14]
I'm implementing a SolarPanel-Fixer for custom Stars into Kopernicus, similar to the StarSystems-Fix. But for this, I need the CelestialBody-Component of my custom Star, which is some sort of broken, or non-existent. Is there any possibility to fix that? I've been trying to fix this for the whole day now, but all I got were bugs. ^^

Best regards!
Thomas (The guy who likes Kopernicus and who is coding too much:D)

**Comment by Teknoman117** [comment]
Do you have a branch on your fork where the code is you are trying to fix?  If so, can you point me towards it?

**Comment by ThomasKerman** [comment]
I'll setup one tomorrow and send you the link. :)

**Comment by ThomasKerman** [comment]
Here is the Branch: https://github.com/ThomasKerman/Kopernicus/tree/StarLightFixer
The Comment https://github.com/ThomasKerman/Kopernicus/commit/4321f1183e36b1f184ed53c58263ebe80432b0be is the StarLightFixer Implementation, the other one fixed my stupidity. :D

**Comment by Teknoman117** [comment]
Addressed in https://github.com/BryceSchroeder/Kopernicus/commit/f3e68b31a44af1b774c54c8a00e6b07dab9c4024
