### ISSUE TITLE
Some Bodies Don't Follow Orbits - If Kerbin Reparented

### ISSUE THREAD

**Issue by Teknoman117** [BryceSchroeder/Kopernicus#15]
If Kerbin is moved from its default position, timewarp in the SpaceCenter doesn't work.  However, it works just fine in the planetarium, flight, and map modes.

**Comment by Teknoman117** [comment]
Also, it seems to randomly time warp with multi-star configs where there are multiple parent "stars" like in star systems

**Comment by Teknoman117** [comment]
Timewarp and actual function are actually completely fine, but the camera's view of the sky is very screwed up.

**Comment by Teknoman117** [comment]
Update: Further analysis of this issue

In the case of a star systems config, or a config where Kerbin is reparented, a handful of bodies don't follow their designated orbits...

**Comment by Teknoman117** [comment]
Holy crap that was a lucky one to notice.

**Comment by Sigma88** [comment]
I'm still seeing this issue as of Kopernicus 0.2.2
was it fixed at any point?

**Comment by ThomasKerman** [comment]
Kinda, but StarLightSwitcher is a hell of a thing, so we can't be sure about this.

**Comment by Olympic1** [comment]
When I saw that you had an issue with this, I tested it with Kerbal Galaxy 2. On my laptop I had 4 bodies with this issue and on my desktop only 1 body.

**Comment by Sigma88** [comment]
I just tried to move kerbin to jool and everything is fine from KSC

I can see jool and the moons wizzing around in the sky

except there's no night/day cycle. It's always the same lighting, and I never see the sun, but that may just be bad timing, I'll have to check

**Comment by ThomasKerman** [comment]
At the moment, that's not really fixable, and we don't want to do it, because we are redoing the StarLightSwitcher, so Logs wouldn't help ;)

**Comment by Sigma88** [comment]
no problem, since it was a closed issue I imagined the reason was something like that.

you're doing an awesome job anyways :D
