### ISSUE TITLE
Recovery distance incorrect

### ISSUE THREAD

**Issue by Nekozji** [BryceSchroeder/Kopernicus#23]
As discussed on the KSP forum at http://forum.kerbalspaceprogram.com/threads/88168-Early-development-0-24-Kopernicus-Planetary-System-Modifier/page68

When using a mod that implements Kopernicus, recovery distances for landed ships are always reported as 942.5km from KSC. It doesn't matter whether you're across the continent, or within a few hundred metres of the VAB.

It's been spotted that this is exactly one quarter of the planet's circumference.

Thanks!

**Comment by Teknoman117** [comment]
Well I've confirmed the existence of this bug.  Darn ... I seriously wonder what is causing this.

**Comment by Teknoman117** [comment]
Well, it appears some code that used to fix an old bug (that apparently doesn't exist anymore) was causing part of the problem.  Now, it always gives you full recovery value =P...

**Comment by Teknoman117** [comment]
okay, this probably has something to do with this...

[LOG 15:41:37]: Injector.Awake(): Completed in: 1851.123 ms
[LOG 15:41:40]: Found Transform: SpaceCenterMarker
[LOG 15:41:40]: Found Transform: KSC
[LOG 15:41:40]: Found Transform: Kerbin
[LOG 15:41:40]: Found Transform: __deactivator

**Comment by Teknoman117** [comment]
Problem solved
