### ISSUE TITLE
Gas giants with rings have translucent edge around them

### ISSUE THREAD

**Issue by CaptRobau** [BryceSchroeder/Kopernicus#29]
OPMs Sarnus and Urlum, the only planets with rings in my mod, have translucent edges that obscure part of the rings and other things such as orbital paths. Both in previous Kopernicus versions as the more recent ones like 0.0.5 and the dev version.

While I haven't tried it on a vacuum body, I do suspect it is related to interplay between the rings and the gas giant's atmosphere.

Image from KopernicusTech version, but it looks the same in my Kopernicus only WIP: http://i.imgur.com/ByHgxgC.png

**Comment by Teknoman117** [comment]
Yeah, I remember seeing this.  I'm pretty sure it's an issue with the drawing order (atmosphere getting draw first).

**Comment by ThomasKerman** [comment]
I'm already working on this Tekno. ;)

**Comment by Teknoman117** [comment]
You find anything yet?

**Comment by ThomasKerman** [comment]
I figured out, that this is related to Unity-Shaders, and found a solution. ATM I'm fixing the last bugs. ;)

----- Ursprüngliche Nachricht -----
Von: "Nathaniel R. Lewis" <notifications@github.com>
Gesendet: ‎01.‎04.‎2015 00:48
An: "BryceSchroeder/Kopernicus" <Kopernicus@noreply.github.com>
Cc: "Dorian Stoll" <dorianstoll@googlemail.com>
Betreff: Re: [Kopernicus] Gas giants with rings have translucent edge aroundthem (#29)

You find anything yet?

**Comment by Teknoman117** [comment]
Sweet.  Was something marked as a non-transparent material (that was supposed to be?)

**Comment by ThomasKerman** [comment]
No, but Unity-Standard-Shader can't merge transparency, so I wrote my own Shader and packed it into the .dll

----- Ursprüngliche Nachricht -----
Von: "Nathaniel R. Lewis" <notifications@github.com>
Gesendet: ‎01.‎04.‎2015 00:53
An: "BryceSchroeder/Kopernicus" <Kopernicus@noreply.github.com>
Cc: "Dorian Stoll" <dorianstoll@googlemail.com>
Betreff: Re: [Kopernicus] Gas giants with rings have translucent edge aroundthem (#29)

Sweet. Was something marked as a non-transparent material (that was supposed to be?)

**Comment by Teknoman117** [comment]
A shader for the rings?

**Comment by ThomasKerman** [comment]
Yes, the transparency is handled by a shader ;)

----- Ursprüngliche Nachricht -----
Von: "Nathaniel R. Lewis" <notifications@github.com>
Gesendet: ‎01.‎04.‎2015 00:55
An: "BryceSchroeder/Kopernicus" <Kopernicus@noreply.github.com>
Cc: "Dorian Stoll" <dorianstoll@googlemail.com>
Betreff: Re: [Kopernicus] Gas giants with rings have translucent edge aroundthem (#29)

A shader for the rings?

**Comment by Teknoman117** [comment]
I meant is shader you wrote applied to the rings

**Comment by ThomasKerman** [comment]
Oh, yes sure. I'm using a custom one.

----- Ursprüngliche Nachricht -----
Von: "Nathaniel R. Lewis" <notifications@github.com>
Gesendet: ‎01.‎04.‎2015 01:01
An: "BryceSchroeder/Kopernicus" <Kopernicus@noreply.github.com>
Cc: "Dorian Stoll" <dorianstoll@googlemail.com>
Betreff: Re: [Kopernicus] Gas giants with rings have translucent edge aroundthem (#29)

I meant is shader you wrote applied to the rings

**Comment by ThomasKerman** [comment]
Fixed with https://github.com/ThomasKerman/Kopernicus/commit/df024dee350126c63a8f7c6128d3c8940a0851a6 ;)
