### ISSUE TITLE
Contracts disappear when contracts non-stock bodies are spawned

### ISSUE THREAD

**Issue by CaptRobau** [BryceSchroeder/Kopernicus#30]
This might no longer be an issue in the new Kopernicus, but in KopernicusTech contracts will (sometimes) disappear when contracts for non-stock bodies are spawned. I haven't been able to replicate it, but it's not easy to replicate anything in career mode anyway so it might still be an issue.

I believe someone mentioned in my thread it had something to do with the flightGlobalsIndex and another in-game numeric identifier for bodies not matching up or something.

**Comment by Teknoman117** [comment]
This is probably an issue with Template instantiated worlds, as the progress tree object will end up getting cloned.  I need to figure out how the backend of the contract system works first.  I can just add an option in Template to "preserve" the contracts (default will be no, so only stock worlds in System.cfg will have to set it true)

**Comment by NathanKell** [comment]
@Teknoman117  Poke me on gchat some time and I can help with that. I had to dig a lot for RP-0 (ended up making my own progress tree in the end). Or just look through the [RP-0 source](https://github.com/KSP-RO/RP-0) that might be enough for you :)

**Comment by CaptRobau** [comment]
This shines a different light on the issue. Might be useful:

http://forum.kerbalspaceprogram.com/threads/104280-0-90-Outer-Planets-Mod-%281-6-5%29-Increased-stability-and-bug-fixes-29-Mar?p=1806390&viewfull=1#post1806390

**Comment by Teknoman117** [comment]
I've just pushed a tentative fix for this.  On stock worlds, the progress tree is preserved (specify removeProgressTree = false in the Template { } config).  Its assumed to be true by default, so custom worlds should automatically generate a new progress tree.

**Comment by Teknoman117** [comment]
Seems I get individual achievements for bodies in the save files.

                        Bastion
                        {
                                reached = 6897425.04035552
                                Orbit
                                {
                                        completed = 6897425.04035552
                                        vessel
                                        {
                                                name = Orbiter 1A
                                                flag = Squad/Flags/default
                                        }
                                        crew
                                        {
                                                crews = Obming Kerman, Kasper Kerman, Podlock Kerman
                                        }
                                }
                        }

**Comment by Teknoman117** [comment]
Uh, just following up, has anyone played through enough to verify that this was fixed?

**Comment by ThomasKerman** [comment]
I don't play career, but some people from the german KSP community play with NewHorizons, and they reported that it works perfect. :)
