### ISSUE TITLE
ScaledSpace cache does not export new PQSMods

### ISSUE THREAD

**Issue by ThomasKerman** [BryceSchroeder/Kopernicus#36]
Situation: I've added a PQSMod to Hodor (VoronoiCraters) but in ScaledSpace I don't see them. Even if I completly remove the check and generate the .bin file for every single planet, nothing happens.

**Comment by ThomasKerman** [comment]
After some more "investigations" I think that Kopernicus really needs a ScaledSpace export button ingame. The reasons: It doesn't generates a Mesh from all applied mods and it sacrifices the quality of the mesh, best example is VoronoiCraters. I think, a user controled, "game-hanging" export button is better than a very low-res ScaledSpace cache.

**Comment by NathanKell** [comment]
Too small to show up on the mesh I'd say,  they'd show up on diffuse and
normal textures.  You exporting those?

Sent by my thumbs, slowly.

**Comment by ThomasKerman** [comment]
I wouldn't say "small": http://i.imgur.com/uivBDlU.jpg That's how it looks in PQS-view.

**Comment by NathanKell** [comment]
Still probably too fine for scaled space mesh to show much,  but if it's
showing zilch.... maybe there is an issue.

Sent by my thumbs, slowly.

**Comment by ThomasKerman** [comment]
If I export the mesh via. Kittopia, it works fine ;)

**Comment by NathanKell** [comment]
I'll shut up now :]

Sent by my thumbs, slowly.

**Comment by ThomasKerman** [comment]
I think I resolved the problem with the Mods not showing up, but the quallity... :D

ScaledSpace: http://i.imgur.com/KjfnOq9.jpg
PQS-View: http://i.imgur.com/FmQE95D.jpg

**Comment by ThomasKerman** [comment]
Fixed with https://github.com/ThomasKerman/Kopernicus/commit/f76d311061355f739b88897df346eb9abb279d4e

Cached ScaledSpace meshes have now the same quality as if they would be exported by Kittopia and a correct scale too.
