### ISSUE TITLE
Invisible Wall Around KSC

### ISSUE THREAD

**Issue by ellbristow** [BryceSchroeder/Kopernicus#44]
I've recently run into this issue while testing aircraft from the runway. While on approach the craft will collide with an invisible wall as it enters the KSC biome approaching the runway... and explodes.

I've testes this a few times and I can't link it to any specific part, altitude or direction... in all cases when approaching the runway (even from the side) the plane explodes.

I'm using New Horizons, and tried it without, but the bug was still there. Testing without Kopernicus, and with all other mods in place, the bug disappeared.

**Comment by ellbristow** [comment]
PS, testing with version 0.0.7, but was the same with the version bundled with the latest version ofNew Horizons (not sure which version that is)

**Comment by ThomasKerman** [comment]
Could you please test this again with Kopernicus installed, but not NewHorizons?

2015-06-06 16:51 GMT+02:00, Elliott Bristow <notifications@github.com>:

**Comment by ellbristow** [comment]
SOrry, I didn't make my explanation clear... I did try without New Horizons, and the bug still occurred... but testing again now to be sure...

**Comment by ellbristow** [comment]
Definitely still happens WITHOUT New Horizons

**Comment by ellbristow** [comment]
It if helps, there is a small glitch when you're exiting the KSC just as you pass the boundary... it's like the aircraft is momentarilly on the ground... literally for a split second.

I'm going to run some tests on vanilla with JUST Kopernicus installed to see if I can still replicate

**Comment by ellbristow** [comment]
OK... replicated with NO mods except Kopernicus

**Comment by NathanKell** [comment]
Ah, crap. @Pingopete reported this too and I totally forgot.

**Comment by ThomasKerman** [comment]
Fixed with https://github.com/BryceSchroeder/Kopernicus/commit/440cd3aa6a2a597de36aa59af25459a0cb7db538
