### ISSUE TITLE
Pre-release vs release

### ISSUE THREAD

**Issue by NathanKell** [BryceSchroeder/Kopernicus#47]
Even though Kopernicus is technically in pre-alpha, in order for CKAN to index releases, releases must not be marked as 'pre-release'. This is why we are unchecking that box.

**Comment by Teknoman117** [comment]
Oh I know why re parenting the star causes things not to update.  For whatever reason, whatever is assigned as the Planetarium.sun object is the root of the walk performed to update bodies.  This is why I had said more work was required.  Basically we also have to manage coronas manually to support multiple visible stars.
