### ISSUE TITLE
Mun has Kerbin's map

### ISSUE THREAD

**Issue by fastdelaspeed** [BryceSchroeder/Kopernicus#49]
At first I thought it was another mod or the configs I had made (which only changed waveLength for atmosphere) but when I tried it in 100% stock it still happens. OpenGL and D3D9 same thing.
![2015-06-24 23_04_22-kerbal space program](https://cloud.githubusercontent.com/assets/13042846/8346086/b77395d2-1ac5-11e5-9910-34286ba2b3bf.png)
![2015-06-24 23_04_30-kerbal space program](https://cloud.githubusercontent.com/assets/13042846/8346087/b77f23c0-1ac5-11e5-9767-f5c8d2898164.png)
![2015-06-24 23_04_40-kerbal space program](https://cloud.githubusercontent.com/assets/13042846/8346088/b789fec6-1ac5-11e5-9807-f0b72fcfafef.png)
As you can see, Kerbin's hightmap. I'm using Kopernicus version 0.0.9, on KSP 1.0.2, with MM 2.6.5

**Comment by NathanKell** [comment]
That's not a heightmap, that's a normal map. You're not in PQS.
At any rate, fixed in 8605a14ab2bdbad32400bfa783e8df9371724117 we just haven't released a new official release yet.
