### ISSUE TITLE
loading stock heightmaps

### ISSUE THREAD

**Issue by Sigma88** [BryceSchroeder/Kopernicus#50]
I am trying to load stock heightmaps with this code

VertexHeightMap
{
	map = BUILTIN/oceanmoon_height
	deformity = 8000
	offset = -2000
	scaleDeformityByRadius = false
	enabled = true
	order = 100
}

but this isn't working

I've tried loading other heightmaps but the result doesn't change.

I was able to load normal_maps and color_maps. but not heightmaps

is this a bug or am I doing something wrong?

**Comment by ThomasKerman** [comment]
Weird.. I'll investigate. ;-)

2015-06-28 18:06 GMT+02:00 Sigma88 <notifications@github.com>:

**Comment by Sigma88** [comment]
thanks! if you need more data I can send you cfgs or whatever you need

knowing where the heightmaps are saved could help me a lot, because I couldn't find them anywhere

**Comment by Teknoman117** [comment]
Again, requesting whether or not this is still an issue as of 0.2.2 (hostfix from Distribution/GameData/)

**Comment by Sigma88** [comment]
I'll check as soon as I get home, sorry for the delay I was not checking github yesterday :)

**Comment by Sigma88** [comment]
yes, the issue persist.
let me know whatever you may need (logs, configs, etc)
I'm at your complete disposal

**Comment by Teknoman117** [comment]
Well it looks like the loader for those got massively modified. Probably something to do with the ondemand system...

**Comment by Sigma88** [comment]
Does this mean that it won't be possible to do that in kopernicus, or do you think it's something fixable?

I am not in any rush. Just would like to know if I should start thinking how to bypass it or just put the project on hiatus for some time and go back to it when (if) this feature will be added

thanks for your time

**Comment by ThomasKerman** [comment]
Could you please try this and report if it works?
`BUILTIN/Laythe/PQSMod_VertexHeightMap/_Height`

**Comment by Sigma88** [comment]
nope, didn't work
could any variation (like removing the "PQS_") help?

**Comment by Sigma88** [comment]
the output log shows this:


AddonLoader: Instantiating addon 'Injector' from assembly 'Kopernicus'
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: texture does not exist! C:/ksp 3/Kerbal Space Program/KSP_Data/../GameData/BUILTIN/Laythe/PQSMod_VertexHeightMap/_Height
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

[Kopernicus]: texture does not exist! C:/ksp 3/Kerbal Space Program/KSP_Data/../GameData/BUILTIN/Laythe/PQSMod_VertexHeightMap/_Height
 
(Filename: C:/buildslave/unity/build/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 56)

**Comment by Sigma88** [comment]
It looks like it doesn't recognize the BUILTIN as a redirect, but looks for a folder named BUILTIN, inside  GameData

**Comment by ThomasKerman** [comment]
Could we get the .log file of the Body you are modifying and your config?

**Comment by Sigma88** [comment]
here's the link
https://www.dropbox.com/s/qao9aehp4ql9vmv/logs.zip

**Comment by ThomasKerman** [comment]
Fixed with https://github.com/BryceSchroeder/Kopernicus/commit/a0895ef52d304911932c0af9f4328e449e34d1d4

**Comment by Sigma88** [comment]
<3

**Comment by Sigma88** [comment]
is there a dll file which I can dowload to test this change?

if so, should I use

map = BUILTIN/Laythe/PQSMod_VertexHeightMap/_Height

?

**Comment by ThomasKerman** [comment]
Currently not, but I'll upload one with the next change :)
The Syntax is correct.

2015-07-12 21:58 GMT+02:00 Sigma88 <notifications@github.com>:

**Comment by Sigma88** [comment]
ok, thank you thomas :)
:+1:
