### ISSUE TITLE
weird terrain feature

### ISSUE THREAD

**Issue by Sigma88** [BryceSchroeder/Kopernicus#51]
I have the same issue this guy posted on OPM's thread

http://forum.kerbalspaceprogram.com/showthread.php?p=2050153#post2050153

my issue come up when I try to edit Kerbin's heightmap.
In the KSC view everything is fine but when I launch a craft the terrain has the same features that can be found on Tal.

I've also posted this issue on the ksp forum.
http://forum.kerbalspaceprogram.com/showthread.php?p=2051227#post2051227

**Comment by Teknoman117** [comment]
Is this still a problem?

**Comment by Sigma88** [comment]
I'll check as soon as I get home :)
I didn't try it in 0.2 yet since I didn't know it was already addressed :+1:

**Comment by Sigma88** [comment]
I just tried and it doesn't seem to show up anymore, but I need to check a couple of things before being 100%

**Comment by Sigma88** [comment]
yeah solved!

thank you guys ;)

closed!
