### ISSUE TITLE
Support navballSwitchRadiusMult

### ISSUE THREAD

**Issue by NathanKell** [BryceSchroeder/Kopernicus#56]
1.0.4 lets you change what multiplier is used to body radius for when to switch the navball from srf to obt. Kopernicus should support it in Properties.
navballSwitchRadiusMult (Default 0.06)

**Comment by ThomasKerman** [comment]
Done with https://github.com/BryceSchroeder/Kopernicus/commit/b987967b1bccfdd377b49e48b3ff33914a11ddec
