### ISSUE TITLE
Questioning the Logic

### ISSUE THREAD

**Issue by Teknoman117** [BryceSchroeder/Kopernicus#58]
Can anyone tell me why this

    // Fix the maximum viewing distance of the map view camera (get the farthest away something can be from the root object)
    PSystemBody rootBody = PSystemManager.Instance.systemPrefab.rootBody;
    double maximumDistance = rootBody.children.Max(b => (b.orbitDriver != null) ? b.orbitDriver.orbit.semiMajorAxis * (1 + b.orbitDriver.orbit.eccentricity) : 0);
    PlanetariumCamera.fetch.maxDistance = ((float)maximumDistance * 3.0f) / ScaledSpace.Instance.scaleFactor;

Got changed to this?

			// Fix the maximum viewing distance of the map view camera (get the farthest away something can be from the root object)
			PSystemBody rootBody = PSystemManager.Instance.systemPrefab.rootBody;
            double maximumDistance = 1000d; // rootBody.children.Max(b => (b.orbitDriver != null) ? b.orbitDriver.orbit.semiMajorAxis * (1 + b.orbitDriver.orbit.eccentricity) : 0);
            if (rootBody != null)
            {
                maximumDistance = rootBody.celestialBody.Radius * 100d;
                if(rootBody.children != null && rootBody.children.Count > 0)
                {
                    foreach (PSystemBody body in rootBody.children)
                    {
                        if (body.orbitDriver != null)
                            maximumDistance = Math.Max(maximumDistance, body.orbitDriver.orbit.semiMajorAxis * (1d + body.orbitDriver.orbit.eccentricity));
                        else
                            Debug.Log("[Kopernicus]: Body " + body.name + " has no orbitdriver!");
                    }
                }
                else
                    Debug.Log("[Kopernicus]: Root body children null or 0");
            }
            else
                Debug.Log("[Kopernicus]: Root body null!");
            Debug.Log("Found max distance " + maximumDistance);
			PlanetariumCamera.fetch.maxDistance = ((float)maximumDistance * 3.0f) / ScaledSpace.Instance.scaleFactor;

The original logic is that the maximum orbital radius of any of the root body's children is going to dwarf that of any child body.  Like Kerbin->Mun is much less than Sun->Kerbin, or Sun->Kerbin much less than Black Hole->Sun.

Also, can we find some common time this weekend to chat (Thomas, NathanKell, Me)?

**Comment by ThomasKerman** [comment]
I actually think that it got changed for Logging-purposes, but honestly I have no idea. @NathanKell changed it and I never asked. :D

----- Ursprüngliche Nachricht -----
Von: "Nathaniel R. Lewis" <notifications@github.com>
Gesendet: ‎10.‎07.‎2015 07:36
An: "BryceSchroeder/Kopernicus" <Kopernicus@noreply.github.com>
Betreff: [Kopernicus] Questioning the Logic (#58)

Can anyone tell me why this
// Fix the maximum viewing distance of the map view camera (get the farthest away something can be from the root object)
PSystemBody rootBody = PSystemManager.Instance.systemPrefab.rootBody;
double maximumDistance = rootBody.children.Max(b => (b.orbitDriver != null) ? b.orbitDriver.orbit.semiMajorAxis * (1 + b.orbitDriver.orbit.eccentricity) : 0);
PlanetariumCamera.fetch.maxDistance = ((float)maximumDistance * 3.0f) / ScaledSpace.Instance.scaleFactor;
Got changed to this?
        // Fix the maximum viewing distance of the map view camera (get the farthest away something can be from the root object)
        PSystemBody rootBody = PSystemManager.Instance.systemPrefab.rootBody;
        double maximumDistance = 1000d; // rootBody.children.Max(b => (b.orbitDriver != null) ? b.orbitDriver.orbit.semiMajorAxis * (1 + b.orbitDriver.orbit.eccentricity) : 0);
        if (rootBody != null)
        {
            maximumDistance = rootBody.celestialBody.Radius * 100d;
            if(rootBody.children != null && rootBody.children.Count > 0)
            {
                foreach (PSystemBody body in rootBody.children)
                {
                    if (body.orbitDriver != null)
                        maximumDistance = Math.Max(maximumDistance, body.orbitDriver.orbit.semiMajorAxis * (1d + body.orbitDriver.orbit.eccentricity));
                    else
                        Debug.Log("[Kopernicus]: Body " + body.name + " has no orbitdriver!");
                }
            }
            else
                Debug.Log("[Kopernicus]: Root body children null or 0");
        }
        else
            Debug.Log("[Kopernicus]: Root body null!");
        Debug.Log("Found max distance " + maximumDistance);
        PlanetariumCamera.fetch.maxDistance = ((float)maximumDistance * 3.0f) / ScaledSpace.Instance.scaleFactor;

**Comment by NathanKell** [comment]
@Teknoman117 the linq version was throwing. This is null safe, and should be identical in terms of result.

**Comment by Sigma88** [comment]
I don't know if this is OT here, but:
yesterday I tried to make a galaxy without reparenting the sun, basically I put the galactic core in orbit around the sun, and the other star systems in orbit around the galactic core

Some of the new stars had an higher SMA compared to the sun, going against the logic that "the maximum orbital radius of any of the root body's children is going to dwarf that of any child body"

The maximum viewing distance was perfect, I don't know if anyone had tested that yet, I thought to post in here just in case it could interest anyone.
