### ISSUE TITLE
Broken energy flow

### ISSUE THREAD

**Issue by AdminAffe** [BryceSchroeder/Kopernicus#59]
Hello there,

I'm using Kopernicus in conjunction with the Outer Planets Mod.
Yesterday I wanted to place a satellite on a orbit around Kerbin and was confused as I got a warning that my ship was running out of charge, although I had deployed two 1x6 solar panels. I noticed that, while having a decent amount of sun exposure, my energy flow was 0, therefore generating no charge.

After rummaging through 60 mods I finally found this mod here to be the culprit.
The following entry in the System.cfg (@e2fd931e1fe0f1a882d98b95a11eb4ff093bd4cd) seems to cause the problem:

        // SolarPowerCurve
        // {
        //     key = 206000000000 0 0 0
        //     key = 13599840256 1 0 0
        //     key = 68773560320 0.5 0 0
        //     key = 0 10 0 0
        // }

After uncommenting the lines, the solar panels will generate charge again.

**Comment by ThomasKerman** [comment]
This is **NOT** recommended.
You have to install the Beta 0.2 and replace it's .dll with the hotfixed one from here: https://github.com/BryceSchroeder/Kopernicus/tree/master/Distribution/GameData/Kopernicus/Plugins

**Comment by AdminAffe** [comment]
Yep, with the hotfix it works as intended. You should probably release an update for ckan soon.
