### ISSUE TITLE
Game alternates between stock sizes and configured system resizes

### ISSUE THREAD

**Issue by lOmicronl** [BryceSchroeder/Kopernicus#60]
I currently have the following issue when I install a Kopernicus mod that does nothing besides resizing stock planets:

- First start: everything stock size.
- Second start: everything properly resized.
- Third start: everything stock size.
- Fourth start: everything properly resized.
- And so on and so forth.

I can reproduce this at will with a fresh stock 1.0.4 instance and no other mods except the Kopernicus mod in question. For example, it works with both Paul Kingtiger's KScale2 and with Eudae55's Kerbol 3.7 for me.

In both cases Kopernicus 0.1 is involved. I have tried manually upating to 0.2.2, but it renders the resizing configs nonfunctional and results in stock sizes every time.

What can I do to help you guys track this down?

**Comment by ThomasKerman** [comment]
We need your output_log.txt / Player.log and the KSPRoot/Logs/ folder from an Instance of KSP where the config fails. Please make two .zips / whatever, one with the logs from Kopernicus 0.1 and one with the logs from Kopernicus 0.2.2.

**Comment by lOmicronl** [comment]
Grrr. Cue Murphy's Law. Of course now that I need to, I can't seem to reproduce it with a fresh install. But I distinctly remember having the issue both times when testing out the two system resizes mentioned in the OP with just stock parts, to try and see how they felt. No other mods were present at the time... well, perhaps KER was, I'm not fully sure. But it's equally likely that I didn't bother adding anything at the time.

I *can* still reproduce it with my current main install, though. So I've bundled up the logs from that. One thing I noticed is that the game outright deletes the KSPRoot/Logs/ folder whenever it's a startup that results in loading with the stock sizes. So while the other two logs are from a startup that resulted in stock sizes, the logs subfolder is not - it's from a startup that worked correctly.

https://dl.dropboxusercontent.com/u/44754370/logs_kopernicus_0_1.zip

I'll add the 0.2.2 logs in a bit, when I have produced them.

**Comment by ThomasKerman** [comment]
It seems that either your KSP hasn't got enough rights to create the Logs/ folder or another mod uses the folder already. You could try the following: 
- Start your KSP in Admin mode and see what happens
- Delete Kopernicus and the Logs/ folder, start KSP and see if a mod writes to it
- Delete one mod, start KSP, see if it works, if not, do it again etc. to find the bugging mod.

**Comment by lOmicronl** [comment]
Starting the game as administrator changes nothing.

However, I have kind of found a temporary workaround: Kopernicus only breaks if the logs folder is present on startup. So if I manually delete the logs folder, the game launches with Kopernicus working correctly, 100% of the time.

So maybe something is deleting the folder on startup, thereby sniping Kopernicus mid-load and causing it to stall? It's strange, because even as local administrator I don't have rights to delete the Kopernicus logfile while it's being accessed by KSP. I'm going to investigate further...

**Comment by lOmicronl** [comment]
Removed all mods except Kopernicus, KScale2, and ModuleManager (the bare minimum). It's now in the exact same configuration as the fresh install I tried earlier. And yet, the problem still persists in this install.

So I went back to the fresh install that worked fine earlier. And boom, suddenly it gets the problem too! I'm confused. =/

Error is still the same, it says "UnauthorizedAccessException: Access to the path "D:/Kerbal Space Program/Test Instance/KSP_Data/../Logs/" is denied" after finishing to load all parts. That's also the exact moment the already present logs folder disappears from the install directory. Less than one second later, the game switches from the loading screen to the main menu.

**Comment by ThomasKerman** [comment]
Maybe try to check the security permissions of the Logs-folder / the KSPRoot folder? I don't have any other ideas...

**Comment by Teknoman117** [comment]
I'm adding exception catching to the logger, gimme a minute to test it.

**Comment by lOmicronl** [comment]
Can't really get 0.2.2 to work. Specifically the DLL. Do I have to compile it or something? just downloading straight from the link in the Kopernicus thread OP gives me a file that's 10% the size of the old DLL and which isn't loaded by KSP at all. I have no idea how any of this works, I'm afraid.

**Comment by ThomasKerman** [comment]
You need to download the Release 0.2 from this link and put the GameData/Kopernicus folder into your GameData folder: https://github.com/BryceSchroeder/Kopernicus/releases/download/beta-02/Kopernicus.0.2.zip

Then you download Hotfix 2 from here and replace the .dll in GameData/Kopernicus/Plugins: https://github.com/BryceSchroeder/Kopernicus/blob/master/Distribution/GameData/Kopernicus/Plugins/Kopernicus.dll?raw=true

**Comment by Teknoman117** [comment]
Okay, I've pushed an updated version with the hardened logger.  Download this file and replace GameData/Kopernicus/Plugins/Kopernicus.dll with it.

https://github.com/BryceSchroeder/Kopernicus/raw/development/Distribution/GameData/Kopernicus/Plugins/Kopernicus.dll

**Comment by lOmicronl** [comment]
@ThomasKerman - that's exactly what I did. The download gave me an 48 kB file to replace the existing 480 kB file with. After I replaced it, KSP wouldn't even acknowledge that a mod named Kopernicus was present.

I just downloaded the DLL Teknoman117 posted, and that one's once again 475 kB in size. Now Kopernicus loads again.

Right now it seems it's not erroring out anymore, but it's way late and I'll test in detail tomorrow.

**Comment by Teknoman117** [comment]
Very strange.  I just downloaded the release Thomas linked to, and the plugin is reported at 466.9 kB, so I dunno what's up on your end... http://imgur.com/j1OgDfgl.png

**Comment by lOmicronl** [comment]
Weird. Maybe the download errored out...

In any case, Teknoman117, it seems that with your DLL in place this issue isn't recurring for the time being. Whatever you did to the logging routines, they seem much more resilient now :)

I'm going to observe the client's behavior for another two or three days and then close this if no more errors crop up.
