### ISSUE TITLE
Reference frame shift between "universal" and "rotational"

### ISSUE THREAD

**Issue by Sigma88** [BryceSchroeder/Kopernicus#63]
I've reported a weird behaviour of KSP (not direcly related to kopernicus)
both in the forum and in the KSP bug tracker

forum: http://forum.kerbalspaceprogram.com/threads/128497

bugtracker: http://bugs.kerbalspaceprogram.com/issues/5234

this was the answer:

"The game uses two reference frames: universal reference frame above 100 km (in Kerbin case, it differs for other bodies), and rotational reference frame below 100 km. Reason for this is to prevent alignment problems with ships landed on surface"

so there should be a parameter that defines at which altitude the reference frame changes.

I've noticed that making custom planets this altitude is copied from the template, would it be possible to assign one manually? Did you ever encountered anything like this?

It's not a major issue, so don't lose too much time on it ;)

keep up the good work

Sigma

**Comment by ThomasKerman** [comment]
Done :) https://github.com/BryceSchroeder/Kopernicus/commit/6e075b032df27fcbdd1b141275f3cf64b71a07ae

**Comment by Sigma88** [comment]
wow, that was quick
:+1:
