### ISSUE TITLE
Planetary rings "ignore" cloud cover

### ISSUE THREAD

**Issue by TicTaccToe** [BryceSchroeder/Kopernicus#65]
When playing with a visual enhancement mod that adds clouds (EVE), when said clouds are viewed through the planets' ring system, cloud cover is wiped away and removed, but only the area viewed through the  rings. All other cloud persists fine.

**Comment by ThomasKerman** [comment]
Could you please try it with this .dll? https://github.com/BryceSchroeder/Kopernicus/blob/development/Kopernicus/Distribution/GameData/Kopernicus/Plugins/Kopernicus.dll

**Comment by TicTaccToe** [comment]
We've switched one problem for another! With that .dll the planet viewed behind the rings is completely gone, as in, no clouds, no visible planet, just the skybox visible through the rings. The planet and clouds essentially become transparent.

**Comment by Tellion** [comment]
Can confirm.

**Comment by Olympic1** [comment]
idem

**Comment by ThomasKerman** [comment]
Seems that I need to figure out which Position in the RenderQueue EVE uses.

**Comment by ThomasKerman** [comment]
Should be fixed with https://github.com/BryceSchroeder/Kopernicus/commit/68ecca32f39da3057a9fe99e7807a7be47128d37
Closing. :)
