### ISSUE TITLE
Main title screen not loading

### ISSUE THREAD

**Issue by torchard96** [BryceSchroeder/Kopernicus#66]
Hi I tried installing Kopernicus 0.2 on my Linux version of KSP, it loads up all the textures and modules but as soon as I get to the loading screen the loading animation spins super fast but won't load. I checked the debug and it's just an infinite loop of "Look rotation viewing vector is zero".

**Comment by ThomasKerman** [comment]
We need your output_log.txt and your KSPRoot/Logs/ folder. :)

**Comment by torchard96** [comment]
https://github.com/torchard96/output_log
I also played around a bit it turns out I only get the infinite loading when I use the Kopernicus Examples, otherwise it just won't load any planets. I'll try and find out exactly what file is causing the issue.

**Comment by ThomasKerman** [comment]
We need your KSPRoot/Logs/ folder as a .zip. Otherwise, we can't help you. ;)

**Comment by torchard96** [comment]
Sorry I'm really new to github, how would I upload a zip file?

**Comment by ThomasKerman** [comment]
You don't have to upload it to GitHub, you can use Dropbox or whatever you
like :)

**Comment by torchard96** [comment]
https://www.dropbox.com/s/bdy0zhiz06yvvqe/KSP.log.tar.gz?dl=0
Sorry about that.

**Comment by ThomasKerman** [comment]
No, we don't need KSP.log, we need **the Logs/ folder, next to KSP.exe (and
KSP.log)**

2015-07-14 20:45 GMT+02:00 torchard96 <notifications@github.com>:

**Comment by torchard96** [comment]
https://www.dropbox.com/s/gcioh4yhjscwtbj/Logs.tar.gz?dl=0

**Comment by ThomasKerman** [comment]
Delete your settings.cfg and generate a new one. It's a known bug. ;)

**Comment by torchard96** [comment]
Thank you so much!

**Comment by ThomasKerman** [comment]
Fixed with https://github.com/BryceSchroeder/Kopernicus/commit/1c09f89cf48dd370446768c9c850dd5765bd082f
