### ISSUE TITLE
Deactivate Orbit Renderer

### ISSUE THREAD

**Issue by Sigma88** [BryceSchroeder/Kopernicus#67]
is there any way to deactivete the orbit renderer?
I went through the OrbitLoader.cs but I couldn't identify anything that may help with that.

I've already tried "color = 0,0,0,0" but this still renders a black orbit.

I don't know if this can help you, but kittopia already did that
https://github.com/KCreator/Kittopiatech_Planeteditor/blob/cfa711bed17b69e8b3b876771c3fd46f983e298f/Source/Planet_GUI.cs

I think the important bit may be this one:

cbBody.orbitDriver.Renderer.drawMode = OrbitRenderer.DrawMode.OFF;

but I'm not sure

**Comment by Sigma88** [comment]
I'm not trying to push or anything, I know you guys work hard on this mod and pressuring you to do even more is far FAR from my intentions :D 

but I'd like to know if I can expect this "enhancement" to be added in a relatively short period of time or if it'll come maybe one day since it has low priority.

I'm asking this because I'm working on a mod and if I knew this was coming sooner rather than later I may start already laying the foundations for this feature to be included.

as always, follow your priorities, your job untill now was outstanding ;)

**Comment by ThomasKerman** [comment]
I've investigated a bit, and it seems that the Game resets the states at Spawn.
I'm closing this one, but I'll see if I want to patch them post spawn in the future. :)

**Comment by Olympic1** [comment]
in KSP 1.1 the orbitrenderer will be completly overhauled, as mentioned in the [Devnote](http://kerbaldevteam.tumblr.com/post/128126888294)

**Comment by Sigma88** [comment]
dang it

that means I'll have to wait even more
