### ISSUE TITLE
baryCenter ScaledSpace shows up in Science Archives

### ISSUE THREAD

**Issue by Sigma88** [BryceSchroeder/Kopernicus#68]
Title is pretty self explanatory.

When using the baryCenter feature you can still find the body in the science archives, and it shows also it's model.

(e.g. if you use jool as a template, you'll see an image of jool)

this is low priority, I just put it here to help tracking the issues

let me know If I should report less stuff :D 

:+1:

**Comment by ThomasKerman** [comment]
Done with https://github.com/BryceSchroeder/Kopernicus/commit/5433b732aaab199aa459739422124969e6d3765e
