### ISSUE TITLE
flightglobalsindex

### ISSUE THREAD

**Issue by Sigma88** [BryceSchroeder/Kopernicus#70]
when using the Sun as a template for a body my KSP freezes in the loading screen (just when the bar hits 100%)

this is easily solvable by adding a flightGlobalsIndex line into the cfg, but still I thought you may want to know :)

**Comment by Olympic1** [comment]
I use the Sun as a template and it loads without any problems

**Comment by ThomasKerman** [comment]
Weird, but Sigma's right, I got my StarSystems config fixed with that. I will add random generation of the flightGlobalsIndex, until they are properly patched.

**Comment by ThomasKerman** [comment]
Sorry, doesn't really works too. I guess you have to add the field until I can find the issue. ;)

**Comment by Sigma88** [comment]
yeah no problems :D 
at least if you get people with this issue you know what to thell them ;)

**Comment by ThomasKerman** [comment]
Fixed with https://github.com/BryceSchroeder/Kopernicus/commit/cfeadb56127789f34324a4e529443e8d1d30a241

**Comment by Sigma88** [comment]
nice!
