### ISSUE TITLE
Texture Problem

### ISSUE THREAD

**Issue by PigExplosion** [BryceSchroeder/Kopernicus#72]
When i load the game with the mod installed my space center becomes a ray of red light. My lander on Duna is floating, and none of the new planets have textures. What did I do wrong?

**Comment by ThomasKerman** [comment]
Sounds like a wrong installed planet pack. Show me a screenshot of your GameData/ folder and upload your logs (output_log.txt / Player.log, KSPRoot/Logs folder)

**Comment by demonicblack** [comment]
i have the same problem and i had no mods installed only thisng i did was add the gamedata file and i cant seem to make it work
