### ISSUE TITLE
cbNameLater doesn't apply to the Scientific Archives

### ISSUE THREAD

**Issue by Sigma88** [BryceSchroeder/Kopernicus#79]
I'm using this .cfg to change the name of the Mun:

@Kopernicus:AFTER[Kopernicus]
{
	@Body[Mun]
	{
		cbNameLater = Luna
	}
}

it works, except that in the scientific archives it still reads "Mun"

in the tracking station instead it's named "Luna"

**Comment by ThomasKerman** [comment]
Well, cbNameLater only changes the CelestialBody.bodyName field, but the archives use another name-field, so I can't do anything against that. But cbNameLater is only needed for Kerbin and Sun, so you can simply change the name = xxx value. :)

**Comment by Sigma88** [comment]
I needed that for the sun :)

but I guess I can live with it staying that way :)
