### ISSUE TITLE
flightGlobalsIndex needs to match the index in FlightGlobals.Bodies[]

### ISSUE THREAD

**Issue by NathanKell** [BryceSchroeder/Kopernicus#8]
That's what it's there for. :)

**Comment by 00Augustus00** [comment]
Hmm. I think ferram4 said something about this when I told him that BetterBuoyancy gave errors if you were in water on Kopernicus-generated planets.

**Comment by NathanKell** [comment]
Yes. That, and any other mod that expects flightGlobalsIndex to actually, y'know, be the index in FlightGlobals.Bodies.

**Comment by Teknoman117** [comment]
I guess I could patch it post launch.  Problem is just it's impractical to say they have to be sequentially defined in configs if people want to mix and match planet packs

**Comment by NathanKell** [comment]
Yeah, best bet would, I guess, be to do a final pass through everything and set indices based on where they actually are.
