### ISSUE TITLE
Flights are getting killed with the addition of planets around stars

### ISSUE THREAD

**Issue by RogueMason** [BryceSchroeder/Kopernicus#81]
So, I've been scratching my head with this one for a week or two, now, and I can't figure out any solution. I don't think it's my config files, as I've checked them over and over again, but I'll include them at the bottom, anyway.

I've added 6 stars to the game, and I can leave them there without them causing any hassle. However, the moment I add a planet to any one of these stars, there are problems. Any flights that are around any of the stars will either be drastically teleported (I've noticed this in only one instance, with a ship around Adamant being moved to a fly-by trajectory of Titania, the star/black hole that had the new planet in previous tests) or killed outright, and those that are killed outright have typically been in orbit of the new planet. Any flights on the surface of the new planet will be unaffected, including flags and Kerbals.

Flights that are around any of the stock celestial bodies are also affected, though seemingly less so. I did notice a ship go missing from Kerbin orbit, so there's no safe haven, really.

I've tested this in my mod-laden x64 install and a fresh x86 install (with just a couple of mods that enable me to actually do the testing). I saw this occurring in both copies of the game, so I'm doubting it's KSP screwing up, and I can't see there being any way that it's the mods I'm using that are messing things up.

Any thoughts? If you need any other files, let me know and I'll try to get them.

----------

Stars: https://www.dropbox.com/sh/izsyebbecwsorli/AACQH7IbfN70ILnLe1LdOgQ5a?dl=0

Test planet (the textures are 8K, just watch out): https://www.dropbox.com/sh/jrhvgmt7fguu71z/AADCD5GGu1kPnGm-NTUngaqGa?dl=0

(Install the planet to AdamantSystem from the Stars download above; config file obviously goes in Config, and the texture folder is to be dropped in, well, Textures)

**Comment by ThomasKerman** [comment]
That's an issue with your config. The SOI's must be extremly well balanced, otherwise, the ships are catapulted out of the system. ;)
Closing since it's not a Kopernicus issue. :)
